# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import csv, copy
from Menu_Goods import Goods
from Menu_Invoice import Invoice
from Menu_CheckOut import CheckOut
from Menu_Chart import Chart



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1419, 824)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.menu_icon = QtWidgets.QWidget(self.centralwidget)
        self.menu_icon.setGeometry(QtCore.QRect(0, 0, 121, 781))
        self.menu_icon.setObjectName("menu_icon")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.menu_icon)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)

        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.menu_nhap = QtWidgets.QPushButton("Kho")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/images/Icons/Insert_goods.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_nhap.setIcon(icon)
        self.menu_nhap.setObjectName("menu_nhap")
        self.verticalLayout_12.addWidget(self.menu_nhap)

        self.menu_thanh_toan = QtWidgets.QPushButton("Thanh toán")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/images/Icons/Icon_checkOut.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_thanh_toan.setIcon(icon1)
        self.menu_thanh_toan.setObjectName("menu_thanh_toan")
        self.verticalLayout_12.addWidget(self.menu_thanh_toan)

        self.menu_don = QtWidgets.QPushButton("Đơn")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/images/Icons/Icon_order.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_don.setIcon(icon1)
        self.menu_don.setObjectName("menu_don")
        self.verticalLayout_12.addWidget(self.menu_don)
        
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.menu_thong_ke = QtWidgets.QPushButton("Thống kê")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/images/Icons/Icon_chart.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_thong_ke.setIcon(icon2)
        self.menu_thong_ke.setObjectName("menu_thong_ke")
        self.verticalLayout_19.addWidget(self.menu_thong_ke)

        spacerItem = QtWidgets.QSpacerItem(90, 25, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_19.addItem(spacerItem)
        self.exit = QtWidgets.QPushButton(self.menu_icon)
        self.exit.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/images/Icons/Icon_exit.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit.setIcon(icon3)
        self.exit.setIconSize(QtCore.QSize(78, 35))
        self.exit.setObjectName("exit")
        self.verticalLayout_19.addWidget(self.exit)
        self.verticalLayout_12.addLayout(self.verticalLayout_19)
        self.menu_layout = QtWidgets.QWidget(self.centralwidget)
        self.menu_layout.setGeometry(QtCore.QRect(110, 10, 1301, 761))
        self.menu_layout.setMinimumSize(QtCore.QSize(1100, 0))
        self.menu_layout.setObjectName("menu_layout")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.menu_layout)
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.widget_search_2 = QtWidgets.QWidget(self.menu_layout)
        self.widget_search_2.setObjectName("widget_search_2")

        

        self.verticalLayout_20.addWidget(self.widget_search_2)
        self.stackedMenuItem = QtWidgets.QStackedWidget(self.menu_layout)
        self.stackedMenuItem.setObjectName("stackedMenuItem")

        self.goods = Goods()
        self.stackedMenuItem.addWidget(self.goods)

        self.checkOut = CheckOut()
        self.stackedMenuItem.addWidget(self.checkOut)
        
        self.invoice = Invoice()
        self.stackedMenuItem.addWidget(self.invoice)

        self.chart = Chart()
        self.stackedMenuItem.addWidget(self.chart)

        self.verticalLayout_20.addWidget(self.stackedMenuItem)
        self.widget_25 = QtWidgets.QWidget(self.centralwidget)
        self.widget_25.setGeometry(QtCore.QRect(570, 730, 77, 38))
        self.widget_25.setObjectName("widget_25")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_25)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1419, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedMenuItem.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menu_nhap.setText(_translate("MainWindow", "Kho"))

    
    def reset_all_list(self):
        
        self.goods.show_list_M1()
        self.checkOut.show_list_M2()
        self.checkOut.show_carts_M2()
        self.checkOut.show_total_M2()
        self.invoice.show_invoice_M3()
        self.chart.update_chart_M4()
    
import source_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
